# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [2]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [9]:
df.groupby("Department")["Salary"].describe()
df.groupby("Department")["Salary"].agg(["mean","max","mean"])

                    mean    max          mean
Department
Finance     61000.000000  65000  61000.000000
HR          51000.000000  52000  51000.000000
IT          72333.333333  75000  72333.333333

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [10]:
# 1. Mean salary per department
print("\nMean salary by Department:")
print(df.groupby("Department")["Salary"].mean())

# 2. Sum of salaries per department
print("\nTotal salary by Department:")
print(df.groupby("Department")["Salary"].sum())

# 3. Count of employees per department
print("\nNumber of employees by Department:")
print(df.groupby("Department")["Employee"].count())

# 4. Multiple aggregations on Salary using agg()
print("\nMultiple aggregations on Salary:")
print(df.groupby("Department")["Salary"].agg(["mean", "max", "min", "count"]))

Mean salary by Department:
Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

Total salary by Department:
Department
Finance    183000
HR         102000
IT         217000
Name: Salary, dtype: int64

Number of employees by Department:
Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

Multiple aggregations on Salary:
                    mean    max    min  count
Department
Finance     61000.000000  65000  58000      3
HR          51000.000000  52000  50000      2
IT          72333.333333  75000  70000      3

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [15]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
result=df.groupby("Department").agg({
    "Salary":["mean","max","min"],
    "Age":["max","min"]})
print(result)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26
                  Salary               Age
                    mean    max    min max min
Department
Finance     61000.000000  65000  58000  35  26
HR          51000.000000  52000  50000  29  28
IT          72333.333333  75000  70000  32  30

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [24]:
pivot_salary = df.pivot_table(values="Salary", index="Department", aggfunc="mean")
print("\nPivot table: Average Salary by Department")
print(pivot_salary)
df["AgeGroup"] = pd.cut(df["Age"], bins=[25, 30, 35, 40], labels=["25-30", "31-35", "36-40"])
crosstab_result = pd.crosstab(df["Department"], df["AgeGroup"])
print(df)
print(crosstab_result)

Pivot table: Average Salary by Department
             Salary
Department
Finance     59000.0
HR          51000.0
IT          69000.0
  Department Employee  Salary  Age     City AgeGroup
0         HR    Alice   50000   28    Delhi    25-30
1         IT      Bob   65000   35   Mumbai    31-35
2    Finance  Charlie   60000   30    Delhi    25-30
3         IT    David   70000   40  Chennai    36-40
4         HR     Emma   52000   26   Mumbai    25-30
5    Finance    Frank   58000   32    Delhi    31-35
6         IT   George   72000   38   Mumbai    36-40
7         HR   Hannah   51000   27    Delhi    25-30
AgeGroup    25-30  31-35  36-40
Department
Finance         1      1      0
HR              3      0      0
IT              0      1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [27]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
data = {
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "IT", "HR"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "George", "Hannah"],
    "Salary": [50000, 65000, 60000, 70000, 52000, 58000, 72000, 51000],
    "Age": [28, 35, 30, 40, 26, 32, 38, 27],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai", "Delhi", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
# 2. Group by Department to get average Salary and max Age
# Write your code here
df.groupby("Department").agg({"Salary":"mean","Age":"max"})
# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here
df.groupby("Department").agg({"Salary":"mean","Age":"max"})
# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here
df.pivot_table( values="Salary",
    index="Department",
    aggfunc="mean")
# 5. Build a crosstab for Department vs City
# Write your code here
pd.crosstab(df["Department"],df["City"])

Original DataFrame:
  Department Employee  Salary  Age     City
0         HR    Alice   50000   28    Delhi
1         IT      Bob   65000   35   Mumbai
2    Finance  Charlie   60000   30    Delhi
3         IT    David   70000   40  Chennai
4         HR     Emma   52000   26   Mumbai
5    Finance    Frank   58000   32    Delhi
6         IT   George   72000   38   Mumbai
7         HR   Hannah   51000   27    Delhi

City        Chennai  Delhi  Mumbai
Department
Finance           0      2       0
HR                0      2       1
IT                1      0       2

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.