# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [1]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Math": [88, 75, 92, 60, 85],
    "Science": [90, 80, 78, 70, 95]
}

df = pd.DataFrame(data)

In [3]:
df["Total"]=df[["Math","Science"]].apply(lambda row:row.sum(),axis=1)
col_mean=df[["Math","Science"]].apply(lambda col:col.mean())
col_mean

Math       80.0
Science    82.6
dtype: float64

In [7]:
def grade(score):
  if score>85:
    return "A"
  elif score >= 80:
      return "B"
  elif score >= 70:
      return "C"
  else:
      return "D"
df["MathGrade"]=df["Math"].apply(grade)
print(df)

      Name  Math  Science  Total MathGrade
0    Alice    88       90    178         A
1      Bob    75       80    155         C
2  Charlie    92       78    170         A
3    David    60       70    130         D
4     Emma    85       95    180         B

In [11]:
df["NameLower"]=df["Name"].map(str.lower)
df["MathsBonus"]=df["Math"].map(lambda maths:maths+5)
df

      Name  Math  Science  Total MathGrade NameLower  MathsBonus
0    Alice    88       90    178         A     alice          93
1      Bob    75       80    155         C       bob          80
2  Charlie    92       78    170         A   charlie          97
3    David    60       70    130         D     david          65
4     Emma    85       95    180         B      emma          90