# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [18]:
import numpy as np
import pandas as pd

# Dataset 1: Product details
df1 = pd.DataFrame({
    "ProductID": [101, 102, 103],
    "ProductName": ["Pen", "Notebook", "Marker"],
    "Price": [10, 50, 30]
})

# Dataset 2: More products (same columns as df1 → good for vertical stacking)
df2 = pd.DataFrame({
    "ProductID": [104, 105],
    "ProductName": ["Pencil", "Eraser"],
    "Price": [5, 8]
})
# Dataset 3: Additional info (different columns → good for horizontal stacking)
df3 = pd.DataFrame({
    "Stock": [100, 60, 80],
    "Rating": [4.5, 4.7, 4.8]
})
pd.concat([df1,df2],axis=0)
pd.concat([df1,df2],axis=1)

   ProductID ProductName  Price  ProductID ProductName  Price
0        101         Pen     10      104.0      Pencil    5.0
1        102    Notebook     50      105.0      Eraser    8.0
2        103      Marker     30        NaN         NaN    NaN

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [19]:
products = pd.concat([df1, df2], ignore_index=True)
sales = pd.DataFrame({
    "ProductID": [101, 102, 104, 106],  # 106 doesn't exist in products
    "UnitsSold": [500, 200, 150, 50]
})
pd.merge(products,sales,on="ProductID",how="inner")
pd.merge(products,sales,on="ProductID",how="outer")

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0      500.0
1        102    Notebook   50.0      200.0
2        103      Marker   30.0        NaN
3        104      Pencil    5.0      150.0
4        105      Eraser    8.0        NaN
5        106         NaN    NaN       50.0

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [24]:
products = pd.concat([df1, df2], ignore_index=True)

# Stock info (different DataFrame, indexed by ProductID)
stock = pd.DataFrame({
    "Stock": [100, 60, 80, 120, 150],
}, index=[101, 102, 103, 104, 105])  # ProductID as index
p_indexed = products.set_index("ProductID")
joined = p_indexed.join(stock)
print("\nJoined DataFrame (products + stock):")
print(joined)
joinednext=products.join(stock,on="ProductID",how="inner")
print(joinednext)

Joined DataFrame (products + stock):
          ProductName  Price  Stock
ProductID
101               Pen     10    100
102          Notebook     50     60
103            Marker     30     80
104            Pencil      5    120
105            Eraser      8    150
   ProductID ProductName  Price  Stock
0        101         Pen     10    100
1        102    Notebook     50     60
2        103      Marker     30     80
3        104      Pencil      5    120
4        105      Eraser      8    150

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [36]:

# 1. Create three DataFrames: Products, Sales, and Revenue
products = pd.DataFrame({
    "ProductID": [101, 102, 103, 104],
    "ProductName": ["Pen", "Notebook", "Pencil", "Eraser"]
})

sales = pd.DataFrame({
    "ProductID": [101, 102, 103, 105],
    "UnitsSold": [200, 150, 300, 50]
})

revenue = pd.DataFrame({
    "ProductID": [101, 102, 104, 105],
    "Revenue": [1000, 2500, 800, 200]
})

print("Products DataFrame:")
print(products)
print("\nSales DataFrame:")
print(sales)
print("\nRevenue DataFrame:")
print(revenue)
# 2. Concatenate them vertically and horizontally
# Write your code here
pd.concat([products,sales])
pd.concat([products,sales],axis=1,ignore_index=True)
# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here
print(pd.merge(sales,revenue,on="ProductID",how="inner"))
print(pd.merge(sales,revenue,on="ProductID",how="left"))
print(pd.merge(sales,revenue,on="ProductID",how="right"))
print(pd.merge(sales,revenue,on="ProductID",how="outer"))
# 4. Join Products with Sales based on index or a key
# Write your code here
merged=products.merge(sales,on="ProductID",how="inner")
# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here
merged.describe()

Products DataFrame:
   ProductID ProductName
0        101         Pen
1        102    Notebook
2        103      Pencil
3        104      Eraser

Sales DataFrame:
   ProductID  UnitsSold
0        101        200
1        102        150
2        103        300
3        105         50

Revenue DataFrame:
   ProductID  Revenue
0        101     1000
1        102     2500
2        104      800
3        105      200
   ProductID  UnitsSold  Revenue
0        101        200     1000
1        102        150     2500
2        105         50      200
   ProductID  UnitsSold  Revenue
0        101        200   1000.0
1        102        150   2500.0
2        103        300      NaN
3        105         50    200.0
   ProductID  UnitsSold  Revenue
0        101      200.0     1000
1        102      150.0     2500
2        104        NaN      800
3        105       50.0      200
   ProductID  UnitsSold  Revenue
0        101      200.0   1000.0
1        102      150.0   2500.0
2        103      300.0      NaN
3        104        NaN    800.0
4        105       50.0    200.0

       ProductID   UnitsSold
count        3.0    3.000000
mean       102.0  216.666667
std          1.0   76.376262
min        101.0  150.000000
25%        101.5  175.000000
50%        102.0  200.000000
75%        102.5  250.000000
max        103.0  300.000000

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.