In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("student_performance.csv")
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

### How many rows and columns are there in the dataset?

In [5]:
df.shape

(1000000, 6)

### Show the first 10 rows of the dataset.

In [6]:
df.head(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
5,6,13.4,65.1,5.0,97.5,A
6,7,26.1,81.8,5.9,100.0,A
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
9,10,18.8,67.6,6.0,80.3,B

### Show the last 10 rows of the dataset.

In [7]:
df.tail(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
999990,999991,15.4,82.8,4.0,86.9,A
999991,999992,30.0,87.4,6.7,100.0,A
999992,999993,26.3,84.6,4.5,100.0,A
999993,999994,20.7,82.4,5.5,99.1,A
999994,999995,15.1,77.0,9.2,80.5,B
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

### What are the column names in the dataset?

In [9]:
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

### What is the maximum value of weekly_self_study_hours?

In [13]:
hours=df['weekly_self_study_hours'].max()
print(hours)

40.0

### Which student studied the most hours in a week?

In [14]:
print(df[df['weekly_self_study_hours']==hours])

        student_id  weekly_self_study_hours  attendance_percentage  \
209            210                     40.0                   68.1
2895          2896                     40.0                   75.7
15843        15844                     40.0                   99.5
18851        18852                     40.0                   91.7
20126        20127                     40.0                   94.1
...            ...                      ...                    ...
971477      971478                     40.0                   74.2
973306      973307                     40.0                   90.0
974300      974301                     40.0                   78.8
976629      976630                     40.0                   93.9
980167      980168                     40.0                   82.6

        class_participation  total_score grade
209                     6.7        100.0     A
2895                    4.2        100.0     A
15843                   8.0        100.0     A
18851                   7.0        100.0     A
20126                   3.0        100.0     A
...                     ...          ...   ...
971477                  7.7        100.0     A
973306                  6.2        100.0     A
974300                  2.5        100.0     A
976629                  7.0        100.0     A
980167                  7.2        100.0     A

[166 rows x 6 columns]

### Show the top 5 students by weekly_self_study_hours.

In [16]:
df.sort_values("weekly_self_study_hours",ascending=False).head(5)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
779223,779224,40.0,76.1,6.4,100.0,A
891941,891942,40.0,72.6,8.8,100.0,A
334965,334966,40.0,92.3,5.4,100.0,A
912897,912898,40.0,100.0,9.1,100.0,A
628230,628231,40.0,93.4,5.2,100.0,A

### Which student has the highest attendance percentage?

In [21]:
df[df['attendance_percentage']==df['attendance_percentage'].max()].head(1)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
7,8,20.4,100.0,4.0,96.1,A

### Which student has the highest class participation?

In [20]:
df[df['class_participation']==df['class_participation'].max()].head(1)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
137,138,12.7,78.3,10.0,78.7,B

### Create a new column score_level
"High" if total_score ≥ 90 , "Medium" if 70 ≤ total_score < 90, "Low" if total_score < 70

In [23]:
def score(marks):
  if marks>=90:
    return "High"
  elif 90<marks or marks>=70:
    return "Medium"
  elif marks<70:
    return "Low"
df["score_level"]=df["total_score"].apply(score)
print(df.head(10))

   student_id  weekly_self_study_hours  attendance_percentage  \
0           1                     18.5                   95.6
1           2                     14.0                   80.0
2           3                     19.5                   86.3
3           4                     25.7                   70.2
4           5                     13.4                   81.9
5           6                     13.4                   65.1
6           7                     26.1                   81.8
7           8                     20.4                  100.0
8           9                     11.7                  100.0
9          10                     18.8                   67.6

   class_participation  total_score grade score_level
0                  3.8         97.9     A        High
1                  2.5         83.9     B      Medium
2                  5.3        100.0     A        High
3                  7.0        100.0     A        High
4                  6.9         92.0     A        High
5                  5.0         97.5     A        High
6                  5.9        100.0     A        High
7                  4.0         96.1     A        High
8                  8.2         69.8     C         Low
9                  6.0         80.3     B      Medium

### Which student has the highest total_score?

In [24]:
df[df['total_score']==df['total_score'].max()].head(1)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level
2,3,19.5,86.3,5.3,100.0,A,High

### How many students scored exactly 100 in total_score?

In [31]:
len(df[df['total_score']==100])

268121

### Make a new column for study efficiency = total_score ÷ weekly_self_study_hours.

In [33]:
df['efficiency'] = df['total_score'] / df['weekly_self_study_hours']
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,efficiency
0,1,18.5,95.6,3.8,97.9,A,High,5.291892
1,2,14.0,80.0,2.5,83.9,B,Medium,5.992857
2,3,19.5,86.3,5.3,100.0,A,High,5.128205
3,4,25.7,70.2,7.0,100.0,A,High,3.891051
4,5,13.4,81.9,6.9,92.0,A,High,6.865672
...,...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High,5.555556
999996,999997,15.7,82.7,6.7,88.3,A,Medium,5.624204
999997,999998,14.2,85.1,5.8,87.9,A,Medium,6.190141
999998,999999,25.3,90.0,5.3,100.0,A,High,3.952569
999999,1000000,18.3,84.6,4.1,100.0,A,High,5.464481

### Create a new column study_category
"Light" if weekly_self_study_hours < 10,
"Moderate" if 10 ≤ hours ≤ 20,
"Heavy" if hours > 20

In [34]:
def studycatagory(hours):
  if hours>20:
    return "Heavy"
  elif hours<20 and hours>=10:
    return "Moderate"
  elif hours<10:
    return "Light"
df["study_category"]=df["weekly_self_study_hours"].apply(studycatagory)
df.head(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,efficiency,study_category
0,1,18.5,95.6,3.8,97.9,A,High,5.291892,Moderate
1,2,14.0,80.0,2.5,83.9,B,Medium,5.992857,Moderate
2,3,19.5,86.3,5.3,100.0,A,High,5.128205,Moderate
3,4,25.7,70.2,7.0,100.0,A,High,3.891051,Heavy
4,5,13.4,81.9,6.9,92.0,A,High,6.865672,Moderate
5,6,13.4,65.1,5.0,97.5,A,High,7.276119,Moderate
6,7,26.1,81.8,5.9,100.0,A,High,3.831418,Heavy
7,8,20.4,100.0,4.0,96.1,A,High,4.710784,Heavy
8,9,11.7,100.0,8.2,69.8,C,Low,5.965812,Moderate
9,10,18.8,67.6,6.0,80.3,B,Medium,4.271277,Moderate